name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    services:
      kafka:
        image: wurstmeister/kafka
        ports:
          - 9092:9092
        options: >
          --env KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
          --env KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

      zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - 2181:2181

      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
          - 15672:15672

      nginx:
        image: nginx
        ports:
          - 80:80

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Build Docker image
        run: docker build -t 3233126674/takeout-master .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-docker-username/your-app-name

      - name: Deploy to Docker
        run: |
          docker-compose down
          docker-compose up -d
